apiVersion: apps/v1
kind: Deployment
metadata:
  name: vkr
  labels:
    app: vkr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vkr
  template:
    metadata:
      labels:
        app: vkr
    spec:
      containers:
        - name: vkr
          image: chelbsik/vkr:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vkr-service
  labels:
    app: vkr
spec:
  selector:
    app: vkr
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
