---
- name: Clone repo
  git:
    repo: https://github.com/deviantony/docker-elk.git
    dest: "/tmp/docker-elk"

- name: Run ELK
  docker_compose:
    project_src: /tmp/docker-elk/
    state: present