---
- name: Services Deployment
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: Update servers
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
        force: yes 
    
    - name: Install apps
      become: yes
      apt:
        name:
          - docker
          - docker-compose
          - python3
          - python3-pip
          - git
        state: latest

    - name: Create group
      become: yes
      group:
        name: docker
        state: present

    - name: Add user to docker group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      
    - name: Restart service
      become: yes
      service: 
        name: docker
        state: restarted

    - name: Install docker SDK
      pip:
        name: 
          - docker
          - docker-compose
        extra_args: --user
        state: present
    
  roles:
   - grafana
   - jenkins
   - zabbix
   - elk